server:
  port: 8080
spring:
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.231.66.120:3306/customerManage?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: xiaokaixian
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  redis:
    host: 111.231.66.120
    port: 6379
    database: 0
    timeout: 60s
    lettuce:
      shutdown-timeout: 100ms
      pool:
        min-idle: 0
        max-active: 8
        max-wait: -1ms
        max-idle: 8
  mvc:
    view:
      prefix: /
      suffix: .jsp